# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x
    - name: Add `nuget.voids.site` nuget source
      run: dotnet nuget add source https://nuget.voids.site/v3/index.json -n nuget.voids.site
    - name: Build
      run: dotnet publish -c Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        path: src/bin
